# preprocessing

In [6]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder를 객체로 생성한 후, fit( ) 과 transform( )으로 label 인코딩 수행. 
 
encoder = LabelEncoder()
encoder.fit(items)

labels = encoder.transform(items)

print('인코딩 변환값:', labels) 
encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3])

인코딩 변환값: [0 1 4 5 3 3 2 2]


array(['전자렌지', '컴퓨터', '믹서', 'TV', '냉장고', '냉장고', '선풍기', '선풍기'], dtype='<U4')

In [7]:
encoder = LabelEncoder()
labels = encoder.fit_transform(items)

print('인코딩 변환값:', labels) 
encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3])

인코딩 변환값: [0 1 4 5 3 3 2 2]


array(['전자렌지', '컴퓨터', '믹서', 'TV', '냉장고', '냉장고', '선풍기', '선풍기'], dtype='<U4')

In [8]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

In [9]:
encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3])

array(['전자렌지', '컴퓨터', '믹서', 'TV', '냉장고', '냉장고', '선풍기', '선풍기'], dtype='<U4')

In [10]:
def get_name(model, num):
    return model.inverse_transform([num])[0]
get_name(encoder, 3)

'선풍기'

In [15]:
# one-hot encoder
from sklearn.preprocessing import OneHotEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환 
encoder = LabelEncoder()
labels = encoder.fit_transform(items) 
labels.shape

# 2차원 데이터로 변환
labels = labels.reshape(-1,1) 
labels.shape

# 원-핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터\n', oh_labels.toarray())
print('원-핫 인코딩 데이터 차원\n', oh_labels.shape)

원-핫 인코딩 데이터
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
 (8, 6)


In [19]:
label_encoded = LabelEncoder().fit_transform(items).reshape(-1,1)
onehot_encoded = OneHotEncoder().fit_transform(label_encoded).toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [20]:
import pandas as pd

df = pd.DataFrame({'items': items})
df

items
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [21]:
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터
0         1          0         0          0           0          0
1         0          1         0          0           0          0
2         0          0         0          0           1          0
3         0          0         0          0           0          1
4         0          0         0          1           0          0
5         0          0         0          1           0          0
6         0          0         1          0           0          0
7         0          0         1          0           0          0

## 피쳐 스케일링과 정규화

In [23]:
# standard scaler
from sklearn.datasets import load_iris

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

print('feature 들의 평균 값\n', iris_df.mean()) 
print('\nfeature 들의 표준편차 값\n', iris_df.std())

feature 들의 평균 값
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 표준편차 값
 sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64


In [26]:
from sklearn.preprocessing import StandardScaler

# StandardScaler객체 생성
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# StandardScaler객체 생성
scaler = StandardScaler()

# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출. 
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names) 

print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 표준편차 값')
print(iris_df_scaled.std())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 표준편차 값
sepal length (cm)    1.00335
sepal width (cm)     1.00335
petal length (cm)    1.00335
petal width (cm)     1.00335
dtype: float64


In [30]:
# MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

# Create MinMaxScaler Instance
scaler = MinMaxScaler()

# Convert to MinMaxScaler dataset.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('Minimum of feature')
print(iris_df_scaled.min())
print('\nMaximun of feature')
print(iris_df_scaled.max())

Minimum of feature
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

Maximun of feature
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


iris 데이터에 대해서

- test 비율을 20%로 하고
- one-hot encoding을 적용하고
- MinMaxScaler를 사용하고
- cv=5로 하고
- 결정트리 모델을 사용하고
- 파라미터는 max_depth와 min_samples_leaf를 변화시켜 학습하고

도출한 베스트 파라미터를 사용하여 테스트 데이터에 대해서 정확도를 측정하시오.

In [60]:
# iris
from sklearn.datasets import load_iris
iris = load_iris()

# minmax-scaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
iris_scaled = scaler.fit_transform(iris.data)

# onehot-encoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
iris_labels = LabelEncoder().fit_transform(iris.target).reshape(-1,1)
iris_encoded = OneHotEncoder().fit_transform(iris_labels).toarray()

# test 20%
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_scaled, iris_encoded, test_size=0.2, random_state=123
)

# btree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dt_clf = DecisionTreeClassifier()

params = {
    'max_depth': [2,3,4],
    'min_samples_leaf': [1,2,3],
}

# GridSearchCV
grid_dtree = GridSearchCV(dt_clf, param_grid=params, cv=5, scoring='accuracy')
grid_dtree.fit(X_train, y_train)

print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도: {0:.4f}'.format(grid_dtree.best_score_))

estimator = grid_dtree.best_estimator_
pred = estimator.predict(X_test)

# accuracy_score
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

GridSearchCV 최적 파라미터: {'max_depth': 4, 'min_samples_leaf': 1}
GridSearchCV 최고 정확도: 0.9417


0.9666666666666667